### ISSUE TITLE
Release a new version with wgpu 22.x

### ISSUE THREAD

**Issue by w4ngzhen** [grovesNL/glyphon#111]
Hello dear author, I noticed that there was a [previous PR](https://github.com/grovesNL/glyphon/pull/106) that has completed the dependency upgrade on wgpu to v22. When will you release a new version on your end? I am very much looking forward to it.

**Comment by ShadowElf37** [comment]
you can include the updated version in your project by adding to Cargo.toml
`glyphon = { git = "https://github.com/grovesNL/glyphon.git" }`

**Comment by w4ngzhen** [comment]
> you can include the updated version in your project by adding to Cargo.toml `glyphon = { git = "https://github.com/grovesNL/glyphon.git" }`

thanks!
