### ISSUE TITLE
Incorrect alpha blending

### ISSUE THREAD

**Issue by BillyDM** [grovesNL/glyphon#112]
It seems that glyphon is not doing proper alpha blending. I've made a small test app that renders small text at a size of 13.0, and the text appears too bold with white text on a black background, and too thin with black text on a white background.

I've made sure to use `TextureFormat::Bgra8UnormSrgb` for my swapchain texture. Does your system have this issue too? Here is the small test application: https://pastebin.com/Bx4bDmvx

![Screenshot_20240814_190646](https://github.com/user-attachments/assets/4a23bf82-9127-4164-9407-7a7171252411)
![Screenshot_20240814_190729](https://github.com/user-attachments/assets/7b2e9071-0868-486e-8f72-819d0d91febc)

**Comment by grovesNL** [comment]
This seems like the same question as https://github.com/iced-rs/iced/issues/2254

It's not clear how to improve this without intentionally doing the wrong thing (force a different color space and alpha blending in a way that seems to look better which you should be able to do outside of glyphon – the equivalent of the `web-colors` feature in iced) or apply advanced techniques earlier in the rasterizer (stem darkening, etc.).

**Comment by BillyDM** [comment]
Ah, I see. I'll look into how Iced solves this then.

**Comment by BillyDM** [comment]
Alright, Ive implemented a `web-colors` feature flag in my vector graphics library and it's working how I want now.

**Comment by grovesNL** [comment]
Ok great! I think we can close this for now then since we already support both formats. Any changes to support stem darkening etc. though would probably happen somewhere upstream.
