### ISSUE TITLE
Doesn't work on web

### ISSUE THREAD

**Issue by GorgWorgington** [grovesNL/glyphon#125]
I added a text overlay using glyphon (0.7.0) to my project and it works fine natively but when I build for web the text doesn't show up at all. I had the same issue as #70 but once I fixed that the text simply wouldn't render on web (both WebGL and WebGPU).

Had the issue on both Chrome and Firefox.

I'm not sure if it's a bug or I'm missing something.

**Comment by grovesNL** [comment]
Is it possible you could share an example? Maybe the [viewport size isn't being updated](https://github.com/grovesNL/glyphon/blob/b2129f1765333156a57e19ed5ddc07d4584188b3/examples/hello-world.rs#L162) when the canvas is resized?

**Comment by GorgWorgington** [comment]
I was able to fix it by resizing the `text_buffer` with `Buffer::set_size()` in the resize event handler. Perhaps that should be done in the example? Either way, your insight was very helpful. Thanks.
