### ISSUE TITLE
Some Source Suggestions.

### ISSUE THREAD

**Issue by genusistimelord** [grovesNL/glyphon#18]
So in small or large projects it does tend to be a good Idea to split structure and data types into their own parts. This makes certain things Easier to find and can improve readability and Adaptability. Keeping most of everything in a Single file generally is a huge turn off to programmers who are willing to help as it makes it harder to find Certain things. This is just a Suggestion not really a Must do. 

TextAtlas and Text Renderer can be split into their own files. The major Data structures at the top Could either Stay since they are small or be moved into a single separate file to remove code form the lib.rs. Some internal Changes Could also be split into Functions as well and just made inlined, which can make Code easier to read if the function names Make sense for what it does. 

Splitting up the Code can also help later on with new Feature Additions to this library. Anyways What do you think?

**Comment by grovesNL** [comment]
Fixed by #19
