### ISSUE TITLE
Handle text overflow

### ISSUE THREAD

**Issue by grovesNL** [grovesNL/glyphon#2]
Handle text overflow outside of layouts through culling and clipping.

Culling:
- We could cull on the CPU, e.g. if all or any glyph's vertex is outside the layout then we could skip it
  - We could also clip on the CPU at this point if we want, see note below

Clipping:
- When one layout is used per `render`, clipping with scissor could be handled outside of glyphon or by glyphon setting the scissor
- When multiple layouts are used, we'd probably need to handle clipping through shader discard or clip on the CPU (e.g. clip the vertices and sample the glyph from the remaining area)

**Comment by madmaxio** [comment]
Line breaks also go here?
