### ISSUE TITLE
Text atlas pipeline sample count 

### ISSUE THREAD

**Issue by junglie85** [grovesNL/glyphon#24]
I have a render pass with MSAA enabled and would like to render text in this pass. Would you be willing to accept a PR to set the sample count as part of the atlas’ `new` function? Is there any reason not to do render text to an MSAA target?

**Comment by grovesNL** [comment]
Hi! :wave: What happens when you try to use a MSAA enabled render pass today? Ideally I don't think the atlas would need to be aware of whether the render pass that uses it will be multisampled, but I might be misunderstanding.

**Comment by junglie85** [comment]
I can’t remember the specific message but it’s something like color attachment expect sample count 4 but pipeline is configured with sample count 1.

You have to set the sample count in the pipeline configuration and the target view of the color attachment has to have the same sample count. The actual output view is assigned to the resolve target of the same color attachment. So I don’t think there is any way to avoid it - but I’m very happy to learn if that turns out to not be the case!

**Comment by junglie85** [comment]
I opened https://github.com/grovesNL/glyphon/pull/25. Happy to discuss.

**Comment by grovesNL** [comment]
This should be fixed with the alternative fix in #27. #27 should allow creating multiple variations (e.g., use in both a MSAA-enabled renderpass and one without)
