### ISSUE TITLE
Feature Request - C API

### ISSUE THREAD

**Issue by VarLad** [grovesNL/glyphon#39]
Would it be feasible to provide a C API of glyphon so it can be easily used by libraries outside Rust?

If its feasible and acceptable, then with some guidance I'm potentially willing to put time into this effort

**Comment by grovesNL** [comment]
I think it would be feasible to have a wrapper crate like `glyphon-c` that exposes a C API, but we probably wouldn't need to keep it inside this repository. Please feel free to try it out and let me know if you run into any problems.
