### ISSUE TITLE
Depth component of a TextArea

### ISSUE THREAD

**Issue by olofwalker** [grovesNL/glyphon#52]
I'm looking to migrate from `wgpu_glyph` to `Glyphon`, but I'm getting stuck on one thing: I can't define a text area's depth value. 

In `wgpu_glyph` I could do something like this:

```
 let section = Section {
                screen_position: pos,
                bounds: size,
                text: vec![Text::new(text)
                    .with_color([c[0], c[1], c[2], 1.0])
                    .with_scale(appearance.font_size)
                    .with_z(z_order.calculate_position())],
                layout: Layout::default_wrap(),
            };
```

where `with_z` would decide the Z written into the depth buffer, a must when doing a UI.

I've seen `prepare_with_depth` but I do not think that lets me set a depth value per textarea ?

**Comment by grovesNL** [comment]
Hi! We need to create a proper example here. In general we're just using `metadata` to pass through something we can use to derive the depth later on.

So you'd set some `metadata` set on the `Attrs` for the buffer, then use `prepare_with_depth` with some function to pull the metadata and get the depth (however you want).

e.g. here's a really simple example where we just pack the depth into metadata directly, but you could do something more complicated if you want to pull depth values from somewhere else (based on a ID, order, etc.):

```rust
let attrs = Attrs::new()
    // Pack the depth into metadata directly
    .metadata(attributes.depth.to_bits() as usize)

buffer.set_text("I have a depth!", attrs);

// Later when the text area is prepared...

renderer.prepare_with_depth(
    /* ... rest of the arguments ... */
    |metadata| {
        // Convert metadata to depth however you'd like
        f32::from_bits(metadata as u32)
    },
);
```

**Comment by olofwalker** [comment]
Thanks, I overlooked the attributes!

Is the idea that the `TextArea` and `Buffer` should be ephemeral? That the `prepare` statement on the `FontRender` class can be called once, and then repeatedly rendered until something changes ?

**Comment by grovesNL** [comment]
Yeah exactly. You can call `prepare` whenever text/attributes change (maybe optimistically if the amount of text is tiny), then re-render as much as you'd like. You could also split into multiple groups of text areas to `prepare`/`render` if their frequency is different, e.g., if you have one label that changes at a high frequency but other text is relatively static.

**Comment by olofwalker** [comment]
Cool, got it.

Just one more question.

What was the rationale for having a reference to the `Buffer` in the `TextArea`? Instead of `Prepare` taking for example a `Vec<(Buffer,TextArea)>` ?

**Comment by grovesNL** [comment]
`Buffer` and `TextArea` can have different update frequencies depending on the application, so I wanted to allow reusing buffers while recreating text areas on-demand. e.g., maybe during a resize the text area bounds change so we want to clip to those new bounds, but we might not want to change the buffer in that case. In practice this means you'd probably cache buffers but recreate text areas somewhere near the `prepare` call.

You can also reuse one `Buffer` across multiple `TextArea`s though that's a pretty niche use case.

**Comment by olofwalker** [comment]
Ok, so for example a UI Widget struct that needs some text drawn, should have a `Buffer` as a member that can later on be referenced by a `TextArea when preparing.

**Comment by grovesNL** [comment]
Yeah exactly, or maybe some buffer cache that's shared between UI widgets depending on the lifecycle of the UI Widget.

**Comment by olofwalker** [comment]
Thanks for your work on this library and answering my questions!
