### ISSUE TITLE
Sharing atlas between multiple text renderers

### ISSUE THREAD

**Issue by grovesNL** [grovesNL/glyphon#6]
Ideally we could have an easy way to have multiple text renderers that share the same atlas to avoid extra texture allocations and share glyphs when possible.

We could do this by passing the atlas to `prepare`, sharing internally, etc. Alternatively we could share a text renderer between all layers, and the text renderer could model layers directly somehow.

**Comment by genusistimelord** [comment]
I would make this into a Texture Array so the Atlas can have many layers to it. otherwise you wont be able to store enough characters for Unicode. Since you should be predefined the size of the character and what font its from within the hash of the characters location within the Textures.
