### ISSUE TITLE
Consider adding a changelog and/or use GitHub releases

### ISSUE THREAD

**Issue by LukasKalbertodt** [grovesNL/glyphon#65]
If I'm not mistaken, there is currently no changelog for this crate. This makes it really hard to update from one version to the next, or even just check what version works with a specific version of wgpu. Adding a changelog would be great, thanks!

**Comment by grovesNL** [comment]
Agreed, there are probably enough projects depending on glyphon that we should try to provide release notes each time. The commit history is generally fairly clean but it would be helpful to summarize it. I'll start doing this for the next release if that sounds reasonable.

**Comment by LukasKalbertodt** [comment]
Thank you! Yes that sounds good :)
