### ISSUE TITLE
Fix interpretation of sRGB colors from cosmic-text Attrs as linear

### ISSUE THREAD

**Issue by jackpot51** [grovesNL/glyphon#69]
You can test this by setting default_color in the hello-world example to #5fafff for example, and then taking a screenshot of the resulting window. You will measure #a4d8ff instead, which means that the default_color is being interpreted as though it is in the linear color space instead of sRGB.

cosmic-text intends for the colors used to be sRGB, and glyphon should also interpret them that way, doing any conversions necessary inside of glyphon.

**Comment by jackpot51** [comment]
I tried to just convert them in the shader https://github.com/jackpot51/glyphon/commit/cd704e6bd5d0ddb815d08358766ad205fd70fada. It works, but this should probably be optional in case other users (like iced) are assuming linear color space.

**Comment by grovesNL** [comment]
That sounds good. I think most people would want to pass sRGB here, so I think we could change it in the next major version without making it optional.

If I'm understanding correctly it looks like `iced` already expects this to be sRGB (https://github.com/iced-rs/iced/blob/99899d49cc93cdec3832f7b5ecad867fdd421e07/graphics/src/text.rs#L155) so this would be an improvement cc @hecrj
