### ISSUE TITLE
WASM browser support?

### ISSUE THREAD

**Issue by dragosrotaru** [grovesNL/glyphon#70]
Hey there, Im working on an IDE and running the example code in this repo, I get an error in the browser:

```panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cosmic-text-0.10.0/src/shape.rs:217:33: no default font found```

What is the best way to deal with loading fonts for Glyphon in the browser?

Thanks :)

**Comment by grovesNL** [comment]
Hi! :wave: On wasm you'd basically load the font directly into your `FontSystem`. I don't have an updated example but it's roughly something like this (API may have changed slightly between versions):
```rust
let mut font_system = FontSystem::new_with_locale_and_db("en-US".into(), fontdb::Database::new());
let font = include_bytes!("fonts/MyFont.ttf");
font_system.db_mut().load_font_data(font);
```

**Comment by dragosrotaru** [comment]
Thanks man, appreciate it :)

**Comment by grovesNL** [comment]
No problem!
