### ISSUE TITLE
wgpu 13 support

### ISSUE THREAD

**Issue by SetheenDev** [grovesNL/glyphon#8]
Hey, I like that this is using the latest shader format.  You might want to add this to Cargo.toml or make mention of it:
```
[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
```

**Comment by grovesNL** [comment]
Thanks for the suggestion! I agree - we can probably just specify the git dependency for now until there's a new release

The 0.1 version that uses wgpu 0.12 is here https://github.com/grovesNL/glyphon/tree/0.1
