### ISSUE TITLE
Release a new version with wgpu 0.20.0 support

### ISSUE THREAD

**Issue by 9291Sam** [grovesNL/glyphon#94]
I noticed that an update to wgpu 0.20.0 was pushed to master earlier today, however no new release was made that can easily be downloaded via cargo.

Thanks for making this library, it's saved me a lot of headache!

**Comment by grovesNL** [comment]
I'll try to make a release soon, please use an override in your `Cargo.toml` or direct dependency on the newest commit rev for now if possible. I'd like to make a decision on #86 and #92 before the next release but should be able to get to that soon.

**Comment by 9291Sam** [comment]
Ahh that makes sense, I figured there was a reason for it, thanks for letting me know!

**Comment by jerzywilczek** [comment]
Is there a possibility of releasing soon? I would really like a release with wgpu 22.0 support

**Comment by grovesNL** [comment]
Released glyphon 0.6.0 with wgpu 22 support https://crates.io/crates/glyphon/
